In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [3]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.2 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [4]:
import pymysql

In [ ]:
#Esercizio1: Dal database AdventureWorks estraiamo la tabella dimproduct • Sulla colonna DealerPrice, utilizzando il metodo .round(), arrotondiamo i valori alle due cifre decimali, e poi al valore intero più vicino • Utilizzando il metodo .clip(), facciamo in modo che i valori siano compresi tra un minimo di 0 e un massimo di 1000

In [ ]:
# Configurazione della connessione
host = 'epicode-data-pt-mysql.cvetyjye2qbl.eu-central-1.rds.amazonaws.com'  # Indirizzo del server MySQL
user = 'studente_dapt'  # Nome utente MySQL
password = 'Ep1c0d3!!D4t4**4n4lys1s'  # Password MySQL
database = 'AdventureWorksDW'  # Nome del database a cui collegarsi

# Creazione della connessione al database
connection = pymysql.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )

query1 = "SELECT * FROM dimproduct"
db_engine = connection.cursor()
df_dimproduct = pd.read_sql_query(query1, connection)
df_dimproduct.head()

<ipython-input-4-5951041df91d>:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dimproduct = pd.read_sql_query(query1, connection)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
1,2,BA-8327,NaN,None,None,Bearing Ball,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
2,3,BE-2349,NaN,None,None,BB Ball Bearing,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
3,4,BE-2908,NaN,None,None,Headset Ball Bearings,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
4,5,BL-2036,NaN,None,None,Blade,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

In [ ]:
#Sulla colonna DealerPrice, utilizzando il metodo .round(), arrotondiamo i valori alle due cifre decimali, e poi al valore intero più vicino
df_dimproduct['DealerPrice'] = df_dimproduct['DealerPrice'].round(2).round()
print(df_dimproduct['DealerPrice'].drop_duplicates())

0         NaN
211      20.0
213      21.0
217       6.0
222       5.0
        ...
560    1430.0
564     445.0
579    1021.0
586     462.0
590     339.0
Name: DealerPrice, Length: 99, dtype: float64

In [ ]:
#Utilizzando il metodo .clip(), facciamo in modo che i valori della colonna dealerprice siano compresi tra un minimo di 0 e un massimo di 1000
df_dimproduct['DealerPrice'] = df_dimproduct['DealerPrice'].clip(lower=0, upper=1000)
print(df_dimproduct['DealerPrice'].drop_duplicates())

0        NaN
211     20.0
213     21.0
217      6.0
222      5.0
       ...
557    243.0
559    729.0
564    445.0
586    462.0
590    339.0
Name: DealerPrice, Length: 89, dtype: float64

In [ ]:
#Esercizio2: Creiamo un DataFrame sintetico, che contiene i guadagni mensili di diverse annate, con il seguente codice: years = 5 a = pd.DataFrame({"Mese": list("GFMAMGLASOND"*years),                "Anno": np.repeat(list(range(years)), 12),                "Guadagni": np.random.randint(800, 5000, 12*years)}) • Calcola la somma cumulativa delle vendite per ogni mese utilizzando il metodo .cumsum() • Come sopra, ma diviso per ogni anno

In [ ]:
years = 5
a = pd.DataFrame({"Mese": list("GFMAMGLASOND"*years),
                   "Anno": np.repeat(list(range(1,6)), 12),
                   "Guadagni": np.random.randint(800, 5000, 12*years)})
print(a)

   Mese  Anno  Guadagni
0     G     1      2603
1     F     1      3556
2     M     1      1681
3     A     1      3332
4     M     1      4244
5     G     1      3933
6     L     1      1227
7     A     1      4203
8     S     1      1621
9     O     1       835
10    N     1      2359
11    D     1      4619
12    G     2      2863
13    F     2      3895
14    M     2      1722
15    A     2      3393
16    M     2      4363
17    G     2      2308
18    L     2      2990
19    A     2      1121
20    S     2      1188
21    O     2      1410
22    N     2      1171
23    D     2      4109
24    G     3      4208
25    F     3      2208
26    M     3      2496
27    A     3       820
28    M     3      3328
29    G     3      3243
30    L     3      3382
31    A     3      3962
32    S     3      2965
33    O     3      4326
34    N     3      2881
35    D     3      1214
36    G     4      1341
37    F     4      4776
38    M     4      1323
39    A     4      3841
40    M     4      4394
41    G     4      3125
42    L     4      3574
43    A     4      3530
44    S     4      4410
45    O     4      2685
46    N     4      2861
47    D     4      2508
48    G     5      4800
49    F     5      1467
50    M     5      2118
51    A     5      1638
52    M     5      1779
53    G     5      2122
54    L     5      1007
55    A     5      2773
56    S     5      4994
57    O     5      4862
58    N     5      2353
59    D     5      3625

In [ ]:
#Calcola la somma cumulativa delle vendite per ogni mese utilizzando il metodo .cumsum()
a['Somma_Cumulativa'] = a['Guadagni'].cumsum()
print(a)

   Mese  Anno  Guadagni  Somma_Cumulativa
0     G     1      2603              2603
1     F     1      3556              6159
2     M     1      1681              7840
3     A     1      3332             11172
4     M     1      4244             15416
5     G     1      3933             19349
6     L     1      1227             20576
7     A     1      4203             24779
8     S     1      1621             26400
9     O     1       835             27235
10    N     1      2359             29594
11    D     1      4619             34213
12    G     2      2863             37076
13    F     2      3895             40971
14    M     2      1722             42693
15    A     2      3393             46086
16    M     2      4363             50449
17    G     2      2308             52757
18    L     2      2990             55747
19    A     2      1121             56868
20    S     2      1188             58056
21    O     2      1410             59466
22    N     2      1171             60637
23    D     2      4109             64746
24    G     3      4208             68954
25    F     3      2208             71162
26    M     3      2496             73658
27    A     3       820             74478
28    M     3      3328             77806
29    G     3      3243             81049
30    L     3      3382             84431
31    A     3      3962             88393
32    S     3      2965             91358
33    O     3      4326             95684
34    N     3      2881             98565
35    D     3      1214             99779
36    G     4      1341            101120
37    F     4      4776            105896
38    M     4      1323            107219
39    A     4      3841            111060
40    M     4      4394            115454
41    G     4      3125            118579
42    L     4      3574            122153
43    A     4      3530            125683
44    S     4      4410            130093
45    O     4      2685            132778
46    N     4      2861            135639
47    D     4      2508            138147
48    G     5      4800            142947
49    F     5      1467            144414
50    M     5      2118            146532
51    A     5      1638            148170
52    M     5      1779            149949
53    G     5      2122            152071
54    L     5      1007            153078
55    A     5      2773            155851
56    S     5      4994            160845
57    O     5      4862            165707
58    N     5      2353            168060
59    D     5      3625            171685

In [ ]:
Somma_Guadagni_per_Anno = a.groupby('Anno')['Guadagni'].sum()
print(Somma_Guadagni_per_Anno)

Anno
1    34213
2    30533
3    35033
4    38368
5    33538
Name: Guadagni, dtype: int64

In [ ]:
# Calcola la somma cumulativa delle vendite per ogni mese, divisa per anno
a['Somma_Cumulativa_per_Anno'] = a.groupby('Anno')['Guadagni'].cumsum()
print(a)

   Mese  Anno  Guadagni  Somma_Cumulativa  Somma_Cumulativa_per_Anno
0     G     1      2603              2603                       2603
1     F     1      3556              6159                       6159
2     M     1      1681              7840                       7840
3     A     1      3332             11172                      11172
4     M     1      4244             15416                      15416
5     G     1      3933             19349                      19349
6     L     1      1227             20576                      20576
7     A     1      4203             24779                      24779
8     S     1      1621             26400                      26400
9     O     1       835             27235                      27235
10    N     1      2359             29594                      29594
11    D     1      4619             34213                      34213
12    G     2      2863             37076                       2863
13    F     2      3895             40971                       6758
14    M     2      1722             42693                       8480
15    A     2      3393             46086                      11873
16    M     2      4363             50449                      16236
17    G     2      2308             52757                      18544
18    L     2      2990             55747                      21534
19    A     2      1121             56868                      22655
20    S     2      1188             58056                      23843
21    O     2      1410             59466                      25253
22    N     2      1171             60637                      26424
23    D     2      4109             64746                      30533
24    G     3      4208             68954                       4208
25    F     3      2208             71162                       6416
26    M     3      2496             73658                       8912
27    A     3       820             74478                       9732
28    M     3      3328             77806                      13060
29    G     3      3243             81049                      16303
30    L     3      3382             84431                      19685
31    A     3      3962             88393                      23647
32    S     3      2965             91358                      26612
33    O     3      4326             95684                      30938
34    N     3      2881             98565                      33819
35    D     3      1214             99779                      35033
36    G     4      1341            101120                       1341
37    F     4      4776            105896                       6117
38    M     4      1323            107219                       7440
39    A     4      3841            111060                      11281
40    M     4      4394            115454                      15675
41    G     4      3125            118579                      18800
42    L     4      3574            122153                      22374
43    A     4      3530            125683                      25904
44    S     4      4410            130093                      30314
45    O     4      2685            132778                      32999
46    N     4      2861            135639                      35860
47    D     4      2508            138147                      38368
48    G     5      4800            142947                       4800
49    F     5      1467            144414                       6267
50    M     5      2118            146532                       8385
51    A     5      1638            148170                      10023
52    M     5      1779            149949                      11802
53    G     5      2122            152071                      13924
54    L     5      1007            153078                      14931
55    A     5      2773            155851                      17704
56    S     5      4994            160845                      22698
57    O     5      4862            165707                      27560
58    N     5      2353            168060                      29913
59    D     5      3625            171685                      33538

In [ ]:
#Esercizio3: Dal database AdventureWorks estraiamo la tabella dimcustomer • Trasformiamo i nomi dei clienti in modo che abbiano solo lettere minuscole, e i cognomi in modo che abbiano solo lettere maiuscole • Sulla colonna EmailAddress, utilizzando il metodo .str.split(), estraiamo nome utente e dominio • Sulla colonna Phone, estraiamo ogni parte del numero (ad es. da "1 (11) 500 555-0162" a ["1", "(11)", "500", "555-0162"]) • Utilizzando il metodo .str.contains(), estraiamo tutti gli indirizzi e-mail che contengono il numero "21"Estraiamo tutti gli indirizzi e-mail che contengono il numero "20" oppure il numero "10" • Calcolare la lunghezza di ogni indirizzo e-mail ed estrarre i dieci più lunghi e i dieci più corti • Modificare il dominio degli indirizzi e-mail da "adventure-works.com" a "aw-db.com" mediante il metodo .str.replace() • Dalla colonna AddressLine1 estraiamo tutti gli indirizzi che contengono la sottostringa "Street"

In [ ]:
# Configurazione della connessione
host = 'epicode-data-pt-mysql.cvetyjye2qbl.eu-central-1.rds.amazonaws.com'  # Indirizzo del server MySQL
user = 'studente_dapt'  # Nome utente MySQL
password = 'Ep1c0d3!!D4t4**4n4lys1s'  # Password MySQL
database = 'AdventureWorksDW'  # Nome del database a cui collegarsi

# Creazione della connessione al database
connection = pymysql.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )

query2 = "SELECT * FROM dimcustomer"
db_engine = connection.cursor()
df_dimcustomer = pd.read_sql_query(query2, connection)
df_dimcustomer.head()

<ipython-input-5-461ea3185c25>:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dimcustomer = pd.read_sql_query(query2, connection)

,CustomerKey,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
0,11000,26,AW00011000,None,Jon,V,Yang,0,1971-10-06,M,...,Professional,Profesional,Cadre,1,0,3761 N. 14th St,None,1 (11) 500 555-0162,2011-01-19,1-2 Miles
1,11001,37,AW00011001,None,Eugene,L,Huang,0,1976-05-10,S,...,Professional,Profesional,Cadre,0,1,2243 W St.,None,1 (11) 500 555-0110,2011-01-15,0-1 Miles
2,11002,31,AW00011002,None,Ruben,None,Torres,0,1971-02-09,M,...,Professional,Profesional,Cadre,1,1,5844 Linden Land,None,1 (11) 500 555-0184,2011-01-07,2-5 Miles
3,11003,11,AW00011003,None,Christy,None,Zhu,0,1973-08-14,S,...,Professional,Profesional,Cadre,0,1,1825 Village Pl.,None,1 (11) 500 555-0162,2010-12-29,5-10 Miles
4,11004,19,AW00011004,None,Elizabeth,None,Johnson,0,1979-08-05,S,...,Professional,Profesional,Cadre,1,4,7553 Harness Circle,None,1 (11) 500 555-0131,2011-01-23,1-2 Miles

In [ ]:
# Trasformiamo i nomi dei clienti in modo che abbiano solo lettere minuscole, e i cognomi in modo che abbiano solo lettere maiuscole
df_dimcustomer['FirstName'] = df_dimcustomer['FirstName'].str.lower()
df_dimcustomer['LastName'] = df_dimcustomer['LastName'].str.upper()
print(df_dimcustomer[['FirstName', 'LastName']].head())

   FirstName LastName
0        jon     YANG
1     eugene    HUANG
2      ruben   TORRES
3    christy      ZHU
4  elizabeth  JOHNSON

In [ ]:
# Sulla colonna EmailAddress, utilizzando il metodo .str.split(), estraiamo nome utente e dominio
df_dimcustomer[['Username', 'Domain']] = df_dimcustomer['EmailAddress'].str.split('@', expand=True)
print(df_dimcustomer[['Username', 'Domain']].head())

     Username               Domain
0       jon24  adventure-works.com
1    eugene10  adventure-works.com
2     ruben35  adventure-works.com
3   christy12  adventure-works.com
4  elizabeth5  adventure-works.com

In [ ]:
# Sulla colonna Phone, estraiamo ogni parte del numero (ad es. da "1 (11) 500 555-0162" a ["1", "(11)", "500", "555-0162"])
df_dimcustomer['Phone_Parts'] = df_dimcustomer['Phone'].str.split(' ')
print(df_dimcustomer['Phone_Parts'].head())

0    [1, (11), 500, 555-0162]
1    [1, (11), 500, 555-0110]
2    [1, (11), 500, 555-0184]
3    [1, (11), 500, 555-0162]
4    [1, (11), 500, 555-0131]
Name: Phone_Parts, dtype: object

In [ ]:
# Utilizzando il metodo .str.contains(), estraiamo tutti gli indirizzi e-mail che contengono il numero "21"
df_dimcustomer_21 = df_dimcustomer[df_dimcustomer['EmailAddress'].str.contains('21')]
print(df_dimcustomer_21['EmailAddress'].head())

# Estraiamo tutti gli indirizzi e-mail che contengono il numero "20" oppure il numero "10"
df_dimcustomer_20_10 = df_dimcustomer[df_dimcustomer['EmailAddress'].str.contains('20|10')]
print(df_dimcustomer_20_10['EmailAddress'].head())

64        chase21@adventure-works.com
118       alvin21@adventure-works.com
130    caroline21@adventure-works.com
163     gabriel21@adventure-works.com
203        luis21@adventure-works.com
Name: EmailAddress, dtype: object
1        eugene10@adventure-works.com
10    jacquelyn20@adventure-works.com
22        ethan20@adventure-works.com
30      bethany10@adventure-works.com
32       denise10@adventure-works.com
Name: EmailAddress, dtype: object

In [ ]:
# Calcolare la lunghezza di ogni indirizzo e-mail
df_dimcustomer['Email_Length'] = df_dimcustomer['EmailAddress'].str.len()

# Estrarre i dieci più lunghi
df_dimcustomer_longest = df_dimcustomer.sort_values(by='Email_Length', ascending=False).head(10)
print(df_dimcustomer_longest[['EmailAddress', 'Email_Length']])

# Estrarre i dieci più corti
df_dimcustomer_shortest = df_dimcustomer.sort_values(by='Email_Length').head(10)
print(df_dimcustomer_shortest[['EmailAddress', 'Email_Length']])

                            EmailAddress  Email_Length
9242   christopher11@adventure-works.com            33
2655   christopher23@adventure-works.com            33
14964  christopher26@adventure-works.com            33
3512   christopher27@adventure-works.com            33
17017  christopher15@adventure-works.com            33
13417  christopher14@adventure-works.com            33
10233  christopher24@adventure-works.com            33
16661  christopher17@adventure-works.com            33
1767   christopher18@adventure-works.com            33
8768   christopher12@adventure-works.com            33
                   EmailAddress  Email_Length
3974     k0@adventure-works.com            22
15299    y0@adventure-works.com            22
1658   joy2@adventure-works.com            24
550    deb4@adventure-works.com            24
13888  roy9@adventure-works.com            24
6264   ian1@adventure-works.com            24
2326   bob8@adventure-works.com            24
13825  zoe3@adventure-works.com            24
215    ana7@adventure-works.com            24
11213  jay9@adventure-works.com            24

In [ ]:
# Modificare il dominio degli indirizzi e-mail da "adventure-works.com" a "aw-db.com" mediante il metodo .str.replace()
df_dimcustomer['EmailAddress'] = df_dimcustomer['EmailAddress'].str.replace('adventure-works.com', 'aw-db.com')
print(df_dimcustomer['EmailAddress'].head())

0         jon24@aw-db.com
1      eugene10@aw-db.com
2       ruben35@aw-db.com
3     christy12@aw-db.com
4    elizabeth5@aw-db.com
Name: EmailAddress, dtype: object

In [ ]:
# Dalla colonna AddressLine1 estraiamo tutti gli indirizzi che contengono la sottostringa "Street"
df_dimcustomer_street = df_dimcustomer[df_dimcustomer['AddressLine1'].str.contains('Street')]
print(df_dimcustomer_street['AddressLine1'].head())

7        942 Brook Street
12      4785 Scott Street
32     626 Bentley Street
63     4927 Virgil Street
125    8481 Zartop Street
Name: AddressLine1, dtype: object

In [ ]:
#Esercizio4: Dai beginner_datasets carichiamo in un DataFrame il file facebook.csv, che contiene dei post con data di pubblicazione, tipo (foto, video, …) e numero di reactions raccolte: • Con la funzione pd.to_datetime() convertiamo la colonna status_published in formato Timestamp • Utilizzando il metodo .df.strftime(), formatta le date delle pubblicazioni in un formato specifico (ad esempio, "%Y-%m-%d %H:%M:%S"). • Utilizzando gli attributi .dt.year , .dt.month , .dt.day , .dt.dayofweek , .dt.dayofyear, ottieniamo informazioni specifiche sulle date delle transazioni, come l'anno, il mese, il giorno della settimana, il giorno dell'anno, ecc.• Estraiamo solo i post relativi al 2012 • Estraiamo solo i post relativi a maggio 2018 • Confrontiamo il numero di post pubblicati nei weekend rispetto al numero di post pubblicati nel resto della settimana • Troviamo il primo e ultimo post pubblicati in ogni anno • Utilizzando il metodo .tz_localize(), aggiungiamo un fuso orario alle date delle transazioni • Calcoliamo la differenza di tempo tra due transazioni • Quanti tipi di post ci sono? E quanti per ogni tipo?

In [5]:
from google.colab import files
uploaded = files.upload()

Saving facebook.csv to facebook.csv

In [6]:
import io
df_facebook = pd.read_csv(io.BytesIO(uploaded['facebook.csv']))
df_facebook.head()

,status_id,status_type,status_published,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys
0,246675545449582_1649696485147474,video,4/22/2018 6:00,529,512,262,432,92,3,1,1,0
1,246675545449582_1649426988507757,photo,4/21/2018 22:45,150,0,0,150,0,0,0,0,0
2,246675545449582_1648730588577397,video,4/21/2018 6:17,227,236,57,204,21,1,1,0,0
3,246675545449582_1648576705259452,photo,4/21/2018 2:29,111,0,0,111,0,0,0,0,0
4,246675545449582_1645700502213739,photo,4/18/2018 3:22,213,0,0,204,9,0,0,0,0

In [8]:
# Con la funzione pd.to_datetime() convertiamo la colonna status_published in formato Timestamp

df_facebook['status_published'] = pd.to_datetime(df_facebook['status_published'])

In [ ]:
#Utilizzando il metodo .df.strftime(), formatta le date delle pubblicazioni in un formato specifico (ad esempio, "%Y-%m-%d %H:%M:%S")

df_facebook['status_published_formatted'] = df_facebook['status_published'].dt.strftime("%Y-%m-%d %H:%M:%S")
print(df_facebook[['status_published', 'status_published_formatted']].head())

     status_published status_published_formatted
0 2018-04-22 06:00:00        2018-04-22 06:00:00
1 2018-04-21 22:45:00        2018-04-21 22:45:00
2 2018-04-21 06:17:00        2018-04-21 06:17:00
3 2018-04-21 02:29:00        2018-04-21 02:29:00
4 2018-04-18 03:22:00        2018-04-18 03:22:00

In [ ]:
# Ottieniamo informazioni specifiche sulle date delle transazioni
df_facebook['Year'] = df_facebook['status_published'].dt.year
df_facebook['Month'] = df_facebook['status_published'].dt.month
df_facebook['Day'] = df_facebook['status_published'].dt.day
df_facebook['DayOfWeek'] = df_facebook['status_published'].dt.dayofweek
df_facebook['DayOfYear'] = df_facebook['status_published'].dt.dayofyear
print(df_facebook[['status_published', 'Year', 'Month', 'Day', 'DayOfWeek', 'DayOfYear']].head())

     status_published  Year  Month  Day  DayOfWeek  DayOfYear
0 2018-04-22 06:00:00  2018      4   22          6        112
1 2018-04-21 22:45:00  2018      4   21          5        111
2 2018-04-21 06:17:00  2018      4   21          5        111
3 2018-04-21 02:29:00  2018      4   21          5        111
4 2018-04-18 03:22:00  2018      4   18          2        108

In [ ]:
# Estraiamo solo i post relativi al 2012
df_facebook_2012 = df_facebook[df_facebook['Year'] == 2012]
print(df_facebook_2012.head())

                            status_id status_type    status_published  \
2046  246675545449582_303160673134402       photo 2012-12-23 03:11:00
2047  246675545449582_302341609882975       photo 2012-12-21 06:02:00
2048  246675545449582_299212316862571       photo 2012-12-13 11:36:00
2049  246675545449582_290159194434550       photo 2012-11-18 09:50:00
2050  246675545449582_290154177768385       photo 2012-11-18 09:16:00

      num_reactions  num_comments  num_shares  num_likes  num_loves  num_wows  \
2046              0             0           0          0          0         0
2047              4             1           0          4          0         0
2048              3             0           0          3          0         0
2049              5             1           1          5          0         0
2050              2             0           0          2          0         0

      num_hahas  num_sads  num_angrys status_published_formatted  Year  Month  \
2046          0         0           0        2012-12-23 03:11:00  2012     12
2047          0         0           0        2012-12-21 06:02:00  2012     12
2048          0         0           0        2012-12-13 11:36:00  2012     12
2049          0         0           0        2012-11-18 09:50:00  2012     11
2050          0         0           0        2012-11-18 09:16:00  2012     11

      Day  DayOfWeek  DayOfYear
2046   23          6        358
2047   21          4        356
2048   13          3        348
2049   18          6        323
2050   18          6        323

In [ ]:
# Estraiamo solo i post relativi a maggio 2018
df_facebook_may_2018 = df_facebook[(df_facebook['Year'] == 2018) & (df_facebook['Month'] == 5)]
print(df_facebook_may_2018.head())

                            status_id status_type    status_published  \
2690  134115277150304_264554297439734       photo 2018-05-31 12:17:00
2691  134115277150304_264493694112461       photo 2018-05-31 08:37:00
2692  134115277150304_264416247453539       photo 2018-05-31 03:12:00
2693  134115277150304_264168277478336       photo 2018-05-30 08:46:00
2694  134115277150304_264160757479088       photo 2018-05-30 08:24:00

      num_reactions  num_comments  num_shares  num_likes  num_loves  num_wows  \
2690             11             0           0         10          0         1
2691             56             4           2         55          1         0
2692             72            13           1         69          3         0
2693             10             0           0         10          0         0
2694             56             3          12         54          2         0

      num_hahas  num_sads  num_angrys status_published_formatted  Year  Month  \
2690          0         0           0        2018-05-31 12:17:00  2018      5
2691          0         0           0        2018-05-31 08:37:00  2018      5
2692          0         0           0        2018-05-31 03:12:00  2018      5
2693          0         0           0        2018-05-30 08:46:00  2018      5
2694          0         0           0        2018-05-30 08:24:00  2018      5

      Day  DayOfWeek  DayOfYear
2690   31          3        151
2691   31          3        151
2692   31          3        151
2693   30          2        150
2694   30          2        150

In [ ]:
# Confrontiamo il numero di post pubblicati nei weekend rispetto al numero di post pubblicati nel resto della settimana
weekend_posts = df_facebook[df_facebook['DayOfWeek'].isin([5, 6])]  # 5 = sabato, 6 = domenica
weekday_posts = df_facebook[~df_facebook['DayOfWeek'].isin([5, 6])]

print(f"Numero di post pubblicati nei weekend: {len(weekend_posts)}")
print(f"Numero di post pubblicati nei giorni feriali: {len(weekday_posts)}")

Numero di post pubblicati nei weekend: 2041
Numero di post pubblicati nei giorni feriali: 5009

In [ ]:
# Troviamo il primo e ultimo post pubblicati in ogni anno
first_posts = df_facebook.loc[df_facebook.groupby('Year')['status_published'].idxmin()]
last_posts = df_facebook.loc[df_facebook.groupby('Year')['status_published'].idxmax()]
print(first_posts[['status_published', 'Year']])
print(last_posts[['status_published', 'Year']])

        status_published  Year
2634 2012-07-15 02:51:00  2012
2045 2013-01-02 02:23:00  2013
1545 2014-01-05 09:23:00  2014
1312 2015-01-02 03:41:00  2015
974  2016-01-03 04:23:00  2016
434  2017-01-02 08:25:00  2017
3264 2018-01-01 01:39:00  2018
        status_published  Year
2046 2012-12-23 03:11:00  2012
1546 2013-12-31 23:38:00  2013
1313 2014-12-10 07:42:00  2014
976  2015-12-31 08:20:00  2015
435  2016-12-31 05:13:00  2016
3265 2017-12-31 22:15:00  2017
4730 2018-06-13 01:12:00  2018

In [10]:
# Utilizzando il metodo .tz_localize(), aggiungiamo un fuso orario alle date delle transazioni
df_facebook['status_published_localized'] = df_facebook['status_published'].dt.tz_localize('Europe/Rome', nonexistent='NaT')
print(df_facebook[['status_published', 'status_published_localized']].head())

     status_published status_published_localized
0 2018-04-22 06:00:00  2018-04-22 06:00:00+02:00
1 2018-04-21 22:45:00  2018-04-21 22:45:00+02:00
2 2018-04-21 06:17:00  2018-04-21 06:17:00+02:00
3 2018-04-21 02:29:00  2018-04-21 02:29:00+02:00
4 2018-04-18 03:22:00  2018-04-18 03:22:00+02:00

In [11]:
# Calcoliamo la differenza di tempo tra due transazioni
time_diff = df_facebook['status_published'].diff()
print(time_diff.head())

0                 NaT
1   -1 days +16:45:00
2   -1 days +07:32:00
3   -1 days +20:12:00
4   -3 days +00:53:00
Name: status_published, dtype: timedelta64[ns]

In [12]:
# Quanti tipi di post ci sono? E quanti per ogni tipo?
post_types = df_facebook['status_type'].value_counts()
print(post_types)

status_type
photo     4288
video     2334
status     365
link        63
Name: count, dtype: int64

In [ ]:
#Esercizio5: Dai beginner_dataset carichiamo in un DataFrame il file pokemon.csv: • Tramite i metodi .isnull() e .sum() controlliamo se ci sono valori nulli nel dataset e contiamo quanti valori nulli ci sono in ogni colonna • Ci sono valori nulli? • Se sì, avrebbe senso cercare di riempirli? • Eliminiamo le righe che contengono valori nulli

In [13]:
from google.colab import files
uploaded = files.upload()

Saving pokemon.csv to pokemon.csv

In [14]:
import io
df_pokemon = pd.read_csv(io.BytesIO(uploaded['pokemon.csv']))
df_pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [18]:
# Controlliamo se ci sono valori nulli nel dataset e contiamo quanti valori nulli ci sono in ogni colonna
null_values = df_pokemon.isnull().sum()
print(null_values)

# Ci sono valori nulli?
if null_values.sum() > 0:
  print("Ci sono valori nulli nel dataset.")
else:
  print("Non ci sono valori nulli nel dataset.")

# Se sì, avrebbe senso cercare di riempirli?
# Dipende dal contesto e dal tipo di dati. In questo caso, potrebbe avere senso riempire i valori nulli con la media, la mediana o il valore più frequente per le colonne numeriche. Per le colonne categoriche, potrebbe essere necessario riempire i valori nulli con una categoria "Unknown" o eliminarle.

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64
Ci sono valori nulli nel dataset.

In [23]:
# Eliminiamo le righe che contengono valori nulli
df_pokemon_cleaned = df_pokemon.dropna()
print(df_pokemon_cleaned.isnull().sum())

#             0
Name          0
Type 1        0
Type 2        0
Total         0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

In [ ]:
#Esercizio6: Dai beginner_dataset carichiamo in un DataFrame il file automobile.csv: • Ci sono valori nulli? Dove? Quanti? • Quali righe hanno un valore nullo nella colonna num-of-doors? • Esaminando i dati, cerchiamo dei valori da sostituire ai valori nulli nella colonna num-of-doors

In [24]:
from google.colab import files
uploaded = files.upload()

Saving automobile.csv to automobile.csv

In [25]:
import io
df_automobile = pd.read_csv(io.BytesIO(uploaded['automobile.csv']))
df_automobile.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [26]:
# Ci sono valori nulli? Dove? Quanti?
null_values = df_automobile.isnull().sum()
print(null_values)

symboling             0
normalized-losses    37
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  0
stroke                0
compression-ratio     0
horsepower            0
peak-rpm              0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [27]:
# Quali righe hanno un valore nullo nella colonna num-of-doors?
null_doors = df_automobile[df_automobile['num-of-doors'].isnull()]
print(null_doors)

    symboling  normalized-losses   make fuel-type aspiration num-of-doors  \
26          1              148.0  dodge       gas      turbo          NaN
60          0                NaN  mazda    diesel        std          NaN

   body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
26      sedan          fwd           front        93.7  ...           98
60      sedan          fwd           front        98.8  ...          122

    fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
26         mpfi  3.03    3.39               7.6        102      5500       24
60          idi  3.39    3.39              22.7         64      4650       36

   highway-mpg  price
26          30   8558
60          42  10795

[2 rows x 26 columns]

In [28]:
# Esaminando i dati, cerchiamo dei valori da sostituire ai valori nulli nella colonna num-of-doors
# Possiamo vedere che i valori nulli sono presenti in due righe.
# In entrambe le righe, la colonna 'body-style' ha il valore 'hatchback'.
# Possiamo quindi cercare la moda (il valore più frequente) della colonna 'num-of-doors' per i veicoli con 'body-style' = 'hatchback'.

# Troviamo la moda della colonna 'num-of-doors' per i veicoli con 'body-style' = 'hatchback'
mode_doors = df_automobile[df_automobile['body-style'] == 'hatchback']['num-of-doors'].mode()[0]

# Sostituiamo i valori nulli nella colonna 'num-of-doors' con la moda trovata
df_automobile['num-of-doors'].fillna(mode_doors, inplace=True)

# Verifichiamo se ci sono ancora valori nulli nella colonna 'num-of-doors'
print(df_automobile['num-of-doors'].isnull().sum())

0

In [ ]:
#Esercizio7: Abbiamo il seguente DataFrame che raccoglie le misurazioni di un sensore che misura la temperatura atmosferica giornaliera: import numpy as np, pandas as pd temp = pd.DataFrame({"Giorno": [0, 1, 2, 3, 4, 5, 6                                7, 8, 9, 10, 11, 12],       "Temperature": [18, 19, 18, np.nan, 21, 20, 20,                       np.nan, 21, 23, np.nan, 23, 24]}) • Il sensore a volte non funziona, dunque alcuni dati sono mancanti: quale sarebbe la migliore strategia per gestirli?

In [32]:
temp = pd.DataFrame({"Giorno": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],"Temperature": [18, 19, 18, np.nan, 21, 20, 20, np.nan, 21, 23, np.nan, 23, 24]})
print(temp)

    Giorno  Temperature
0        0         18.0
1        1         19.0
2        2         18.0
3        3          NaN
4        4         21.0
5        5         20.0
6        6         20.0
7        7          NaN
8        8         21.0
9        9         23.0
10      10          NaN
11      11         23.0
12      12         24.0

In [31]:
#Il sensore a volte non funziona, dunque alcuni dati sono mancanti: quale sarebbe la migliore strategia per gestirli?

# La migliore strategia per gestire i dati mancanti dipende dal contesto e dal tipo di dati. In questo caso, potremmo utilizzare la interpolazione lineare per riempire i valori mancanti.

temp['Temperature'].interpolate(method='linear', inplace=True)
print(temp)

    Giorno  Temperature
0        0         18.0
1        1         19.0
2        2         18.0
3        3         19.5
4        4         21.0
5        5         20.0
6        6         20.0
7        7         20.5
8        8         21.0
9        9         23.0
10      10         23.0
11      11         23.0
12      12         24.0

In [ ]:
#Esercizio8: Nel pacchetto os della standard library c'è la funzione os.listdir() che permette di avere la lista dei nomi di file all'interno di una directory; senza input di default li cerca nella directory di lavoro corrente, altrimenti si può passare un path per esaminare una directory specifica, ad esempio os.listdir("mio_progetto/beginner_datasets/") • Nella directory dei beginner_datasets, quali sono i dataset che contengono dati nulli?1. Dovremo usare un ciclo for per esaminare tutti i nomi dei file 2. 3. 4. 5. 6. Dovremo selezionare solo i nomi di file con estensione .csv (quindi usare un costrutto if) Nel corpo dovremo leggere di volta in volta il file in esame, e caricarlo in un DataFrame con la funzione .read_csv() Sul DataFrame dovremo utilizzare il metodo .isna() per trovare la maschera booleana dei dati nulli Dovremo contare i dati nulli, utilizzando .sum(); potremmo doverlo utilizzare più di una volta Dovremo stampare, o memorizzare in una list, solo i nomi dei file che contengono dati nulli

In [41]:
# Inizializza una lista per memorizzare i nomi dei file con dati nulli
files_with_nulls = []

# Scorri i file nella directory
for file in files:
  # Seleziona solo i file con estensione .csv
  if file.endswith(".csv"):
    # Leggi il file in un DataFrame
    df = pd.read_csv(os.path.join(files))
    # Controlla se ci sono dati nulli
    if df.isna().sum().sum() > 0:
      # Aggiungi il nome del file alla lista
      files_with_nulls.append(file)

# Stampa i nomi dei file con dati nulli
print(files_with_nulls)

TypeError: expected str, bytes or os.PathLike object, not list